### ISSUE TITLE
Ngrok bad hash

### ISSUE THREAD

**Issue by werdnanoslen** [currychern/bounti#15]
Running Linux Mint 18.1, 4.8.0-54-generic

Walked through setup, and at ```yarn install``` I get the following error:
```
$ yarn install
yarn install v0.24.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error https://registry.yarnpkg.com/@exponent/ngrok/-/ngrok-2.2.7.tgz: Bad hash. Expected "37fe66f922b1003da2a78c66b7d4d3bc9313e423" but got "6c4a98fb138289a05788ac586676f7f153aecfcd" 
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by werdnanoslen** [comment]
@currychern I ran it again on a different network than the previous run:

```
$ yarn install
yarn install v0.24.5
[1/4] Resolving packages...
[2/4] Fetching packages...
error react-native-scripts@0.0.29: The engine "node" is incompatible with this module. Expected version ">=6".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by currychern** [comment]
Cool! It looks like you're running an older version of node. We're using
version 6+. Can you run *node -v* to check what version of node you have?

To upgrade run the following:

sudo npm cache clean -fsudo npm install -g nsudo n stable

Let me know how this goes.

Best,
Curry

**Comment by werdnanoslen** [comment]
Ah, I haven't run into a node version issue before. Updated to v8.0.0, and everything seemed to install correctly.

**Comment by currychern** [comment]
Awesome! I'm glad you were able to install :)
